name: build and publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install Deps
        run: poetry install
      - name: Publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_API_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
